#!/usr/bin/env node
/* Refreshes src/data/worldbank.json — the offline fallback for the live World Bank charts.

   Usage:  npm run refresh

   Pulls the full annual history (1960 onwards) for each indicator the page uses from the World Bank
   Indicators API and writes it with a fetch timestamp and the latest year available. The page only
   uses this file when api.worldbank.org is unreachable in the browser; live.js slices it to the same
   start year as the live chart. Fails (and writes nothing) if any indicator cannot be fetched, so a
   partial refresh never lands. Run monthly by .github/workflows/refresh-data.yml. */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(root, 'src', 'data', 'worldbank.json');

// Keep in step with liveCharts() in src/live.js.
export const INDICATORS = ['NY.GDP.MKTP.CD', 'NY.GDP.PCAP.CD', 'SP.DYN.LE00.IN', 'IT.NET.USER.ZS'];
const COUNTRY = 'IND', SINCE = 1960;
const url = id => `https://api.worldbank.org/v2/country/${COUNTRY}/indicator/${id}?format=json&per_page=200&date=${SINCE}:${new Date().getFullYear()}`;

async function fetchIndicator(id) {
  const res = await fetch(url(id), { headers: { 'user-agent': 'india-growth-tracker refresh script' } });
  if (!res.ok) throw new Error(`${id}: HTTP ${res.status}`);
  const body = await res.json();
  if (!Array.isArray(body) || !Array.isArray(body[1])) throw new Error(`${id}: unexpected response ${JSON.stringify(body).slice(0, 200)}`);
  const rows = body[1].filter(r => r.value != null).map(r => ({ y: +r.date, v: r.value })).sort((a, b) => a.y - b.y);
  if (!rows.length) throw new Error(`${id}: no data points`);
  return { name: body[1][0].indicator.value, years: rows.map(r => r.y), values: rows.map(r => r.v) };
}

const fetchedAt = new Date().toISOString().slice(0, 10);
const results = await Promise.all(INDICATORS.map(fetchIndicator)); // any rejection aborts the whole run
const previous = JSON.parse(readFileSync(outPath, 'utf8'));

const indicators = {};
INDICATORS.forEach((id, i) => {
  const r = results[i];
  indicators[id] = { name: r.name, source: 'World Bank', sourceType: 'multilateral', asOf: `${r.years.at(-1)} data, fetched ${fetchedAt}`, years: r.years, values: r.values };
});
const out = {
  note: 'Offline fallbacks for the live World Bank charts, used only when api.worldbank.org is unreachable. Generated by `npm run refresh` — do not edit by hand.',
  source: `World Bank Indicators API (https://api.worldbank.org/v2/country/${COUNTRY}/indicator/{id})`,
  fetchedAt,
  indicators
};

// Stable, diff-friendly formatting: one line per array.
const json = JSON.stringify(out, null, 2).replace(/\[\n\s+([\s\S]*?)\n\s+\]/g, (m, inner) => '[' + inner.split(/,\s*\n\s*/).join(', ') + ']');
writeFileSync(outPath, json + '\n');

for (const id of INDICATORS) {
  const prev = previous.indicators?.[id], cur = indicators[id];
  const delta = prev?.years ? ` (was ${prev.years.length} points to ${prev.years.at(-1)})` : '';
  console.log(`${id.padEnd(16)} ${cur.years.length} points, ${cur.years[0]}–${cur.years.at(-1)}${delta}`);
}
console.log(`Wrote ${outPath}`);
